name: Build Ren'Py iOS App

on: push

jobs:
  checkout_repository:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: ${{ github.workspace }}

  setup_renpy_sdk:
    needs: checkout_repository
    runs-on: macos-latest
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v4
        with:
          name: repository
          path: ${{ github.workspace }}
      - name: Cache Ren'Py SDK
        id: cache-renpy
        uses: actions/cache@v3
        with:
          path: renpy
          key: renpy-7.8.7-${{ runner.os }}
          restore-keys: |
            renpy-7.8.7-
      - name: Download Ren'Py SDK
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renpy-sdk.zip https://www.renpy.org/dl/7.8.7/renpy-7.8.7-sdk.zip
          unzip renpy-sdk.zip -d renpy
      - name: Download and install rapt
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o rapt.zip https://www.renpy.org/dl/7.8.7/renpy-7.8.7-rapt.zip
          unzip rapt.zip -d renpy/renpy-7.8.7-sdk
      - name: Download and install renios
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renios.zip https://www.renpy.org/dl/7.8.7/renpy-7.8.7-renios.zip
          unzip renios.zip -d renpy/renpy-7.8.7-sdk
      - name: Download and install renpyweb
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renpyweb.zip https://www.renpy.org/dl/7.8.7/renpy-7.8.7-web.zip
          unzip renpyweb.zip -d renpy/renpy-7.8.7-sdk

  create_ios_directory:
    needs: [checkout_repository, setup_renpy_sdk]
    runs-on: macos-latest
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v4
        with:
          name: repository
          path: ${{ github.workspace }}
      - name: Restore Ren'Py SDK cache
        uses: actions/cache@v3
        with:
          path: renpy
          key: renpy-7.8.7-${{ runner.os }}
      - name: Create and populate iOS directory
        run: |
          cd renpy/renpy-7.8.7-sdk
          ./renpy.sh launcher ios_create "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/ios"
          ./renpy.sh launcher ios_populate "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/ios"
      - name: Upload iOS directory
        uses: actions/upload-artifact@v4
        with:
          name: ios-directory
          path: ${{ github.workspace }}/ios

  build_xcode_project:
    needs: create_ios_directory
    runs-on: macos-latest
    outputs:
      app_path: ${{ steps.get_build_settings.outputs.app_path }}
      product_name: ${{ steps.get_build_settings.outputs.product_name }}
      version: ${{ steps.get_build_settings.outputs.version }}
      bundle_id: ${{ steps.get_build_settings.outputs.bundle_id }}
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v4
        with:
          name: repository
          path: ${{ github.workspace }}
      - name: Download iOS directory
        uses: actions/download-artifact@v4
        with:
          name: ios-directory
          path: ${{ github.workspace }}/ios
      - name: Find Xcode project
        run: |
          XCODEPROJ=$(find "${{ github.workspace }}/ios" -maxdepth 1 -name "*.xcodeproj" | head -n 1)
          if [ -z "$XCODEPROJ" ]; then
            echo "Error: No .xcodeproj file found in ${{ github.workspace }}/ios"
            exit 1
          fi
          XCODEPROJ_NAME=$(basename "$XCODEPROJ")
          SCHEME_NAME="${XCODEPROJ_NAME%.xcodeproj}"
          echo